### PR TITLE
fix issue #88 by adding option to hide Menu bar

### LINKED ISSUE #88: Change menu in Windows and Linux
For some reason the window menu-bar (i.e. the one containing `Gmail Desktop`, `Settings`, etc.) is visible all the time, and there is no option to hide it.

(I don't know if this is by design, or an issue with my window manager, namely `i3`.  I'm using OpenSUSE Tumbleweed, and manually installed the `2.6.1` from the Debian `.deb` by extracting it into a custom folder.)

### PR DESCRIPTION
**Pull request by cyfrost**
This fixes #88 by adding a configurable option to set the visibility of the Menu bar for those who want to change it.

When the Menu bar is hidden, we can hit the Alt key once to bring it up.

image

With Menu bar visible (current look):

image

With Menu bar hidden (new look):

image

Thoughts?

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -84,6 +85,8 @@ function createWindow(): void {
     mainWindow.maximize()
   }
 
+  setAppMenuBarVisibility()
```
Comment (markypython) [inline src/app.ts]: Is this something we can set on the window when creating it with the default value?  Then we can call this function later?

File: src/menu.ts [hunk 2]
```diff
@@ -137,6 +137,15 @@ const applicationMenu: MenuItemConstructorOptions[] = [
           config.set(ConfigKey.LaunchMinimized, checked)
         }
       },
+      {
+        label: 'Hide Menu bar',
```
Comment (markypython) [inline src/menu.ts]: I think it would make sense to add this to the appearance menu.  @timche Thoughts?

File: src/utils.ts [hunk 3]
```diff
@@ -1,9 +1,19 @@
 import { app, BrowserWindow, dialog } from 'electron'
+import config, { ConfigKey } from './config'
 
 export function getMainWindow(): BrowserWindow {
   return BrowserWindow.getAllWindows()[0]
 }
 
+export function setAppMenuBarVisibility(): void {
+  const mainWindow = getMainWindow()
+  if (mainWindow) {
```
Comment (markypython) [inline src/utils.ts]: When would this conditional be false?

Comment (cyfrost) [reply src/utils.ts]: I cannot think of any, my bad. It's a redundant check and will be removed, thanks for pointing it out.

File: src/menu.ts (hunk 2 above)
Comment (cyfrost) [reply src/menu.ts]: You're right, I'll move it there then.

File: src/app.ts (hunk 1 above)
Comment (cyfrost) [reply src/app.ts]: > When the menu is turned off, how do you access it?

As mentioned in the OP, we can hit the Alt key once to bring up the Menu bar. And to keep users informed, this message below will be shown when the User hides the menu bar each time.

image

This will be shown each time the Menu bar is hidden by the user. Should we show this message only once?

Comment (cyfrost) [reply src/app.ts]: > Is this something we can set on the window when creating it with the default value? Then we can call this function later?

Yes, we can set the `autoHideMenuBar` property while creating the window but a separate call to `mainWindow.setMenuBarVisibility(boolean)` is required to make the Alt key work. Without making this call, the Menu bar visibility will be set as per the config value but hitting the Alt key will not bring it up.

**Comment by cyfrost** [comment]
> I noticed that this setting is available on all platforms, but it should only be configurable on Linux and Windows. The menu bar on macOS is integrated on system level on top. Otherwise I'm happy to with this feature.

Ah, thanks for pointing it out. I keep missing the consideration of macOS everytime, silly me! Let me fix this.

**Comment by cyfrost** [comment]
@timche As discussed, [this](https://github.com/timche/gmail-desktop/pull/159/commits/426edad69e8df49b9a8e3d007fed776112c6f607) commit checks for macOS before allowing Menu bar visibility changes.

**Comment by timche** [comment]
Thanks a lot! 👏
